parameters:
- name: endpoint
  type: string

steps:
- task: GitHubRelease@0
  inputs:
    gitHubConnection: ${{ parameters.endpoint }}
    repositoryName: emacs-tree-sitter/elisp-tree-sitter
    isDraft: true
    assetUploadMode: replace
    assets: |
      $(System.DefaultWorkingDirectory)/dist/*.tar.gz
      $(System.DefaultWorkingDirectory)/core/dist/*.tar.gz
      $(System.DefaultWorkingDirectory)/core/tsc-dyn.*
