trigger:
  tags:
    include:
    - '*.*.*'

pr: none

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: emacs-tree-sitter

jobs:

- job: Build
  pool:
    vmImage: $(IMAGE_NAME)
  strategy:
    matrix:
      vs2017-win2016:
        IMAGE_NAME: 'vs2017-win2016'
        DYN_EXT: dll
      macos-10.14-emacs-27.1:
        IMAGE_NAME: 'macos-10.14'
        EVM_EMACS: emacs-27.1
        DYN_EXT: dylib
      ubuntu-18.04-emacs-27.1:
        IMAGE_NAME: 'ubuntu-18.04'
        EVM_EMACS: emacs-27.1
        DYN_EXT: so
  steps:
  - checkout: self
    submodules: true
  - template: .azure-pipelines/steps/setup-rust.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-llvm.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: steps/-build.yml
    parameters:
      target: release
  - template: steps/setup-tree-sitter-cli.yml
  - template: steps/-test.yml
  - template: steps/-save-binaries.yml

- job: Package
  dependsOn: Build
  pool:
    vmImage: macos-10.14
  variables:
    EVM_EMACS: emacs-26.3
  steps:
  - checkout: self
    submodules: true
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: steps/-retrieve-binaries.yml
    parameters:
      extensions:
        - dll
        - dylib
        - so
  - template: steps/-package.yml
  - template: steps/-github-release.yml
    parameters:
      endpoint: emacs-tree-sitter
